#!/bin/sh
root -l -q -b 'GetVN.C+("../MH_toy.root","N1SUB3",    1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFcSUB3", 1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFdSUB3", 1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFeSUB3", 1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFfSUB3", 1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFgSUB3", 1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1EVENSUB3",1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N2SUB3",    1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N3SUB3",    1.2,1.6,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N112GSUB3", 1.2,1.6,false,-1)'

root -l -q -b 'GetVN.C+("../MH_toy.root","N1SUB3",    -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1SUB3",    -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFcSUB3", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFdSUB3", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFeSUB3", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFfSUB3", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFgSUB3", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFcSUB3", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFdSUB3", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFeSUB3", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFfSUB3", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFgSUB3", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1EVENSUB3",-0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N2SUB3",    -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N2SUB3",    -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N3SUB3",    -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N3SUB3",    -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N112GSUB3", -0.8,0.8,false,-1)'

root -l -q -b 'GetVN.C+("../MH_toy.root","N1SUB3",    -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFcSUB3", -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFdSUB3", -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFeSUB3", -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFfSUB3", -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1HFgSUB3", -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N1EVENSUB3",-1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N2SUB3",    -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N3SUB3",    -1.6,-1.2,false,-1)'
root -l -q -b 'GetVN.C+("../MH_toy.root","N112GSUB3", -1.6,-1.2,false,-1)'
