#!/bin/sh
root -l -q -b 'GetVN.C+("../MH.root","N1HFcSUB2", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFdSUB2", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFeSUB2", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFfSUB2", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFgSUB2", -0.8,0.8,false,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFcSUB2", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFdSUB2", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFeSUB2", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFfSUB2", -0.8,0.8,true,-1)'
root -l -q -b 'GetVN.C+("../MH.root","N1HFgSUB2", -0.8,0.8,true,-1)'
