TFile * ampt = new TFile("../MH_AMPT.root");
TFile * data = new TFile("../MH.root");
void N1Correlation(){
  TH2D * h2amptPA = (TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/qA");
  h2amptPA->Divide((TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/wnA"));
  TH2D * h2amptPB = (TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/qB");
  h2amptPB->Divide((TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/wnB"));
  TH1D * h1amptPA = (TH1D *) h2amptPA->ProjectionY("h1amptPA",1,10);
  TH1D * h1amptPB = (TH1D *) h2amptPB->ProjectionY("h1amptPB",1,10);
  h1amptPA->SetMarkerStyle(20);
  h1amptPA->SetMarkerColor(kRed);
  h1amptPB->SetMarkerStyle(21);
  h1amptPB->SetMarkerColor(kBlue);
  TH2D * h2amptMA = (TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/qA");
  h2amptMA->Divide((TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/wnA"));
  TH2D * h2amptMB = (TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/qB");
  h2amptMB->Divide((TH2D *) ampt->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/wnB"));
  TH1D * h1amptMA = (TH1D *) h2amptMA->ProjectionY("h1amptMA",1,10);
  TH1D * h1amptMB = (TH1D *) h2amptMB->ProjectionY("h1amptMB",1,10);
  h1amptMA->SetMarkerStyle(20);
  h1amptMA->SetMarkerColor(kRed);
  h1amptMB->SetMarkerStyle(21);
  h1amptMB->SetMarkerColor(kBlue);
  
  TH2D * h2dataPA = (TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/qA");
  h2dataPA->Divide((TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/wnA"));
  TH2D * h2dataPB = (TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/qB");
  h2dataPB->Divide((TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFp1g/wnB"));
  TH1D * h1dataPA = (TH1D *) h2dataPA->ProjectionY("h1dataPA",1,10);
  TH1D * h1dataPB = (TH1D *) h2dataPB->ProjectionY("h1dataPB",1,10);
  h1dataPA->SetMarkerStyle(20);
  h1dataPA->SetMarkerColor(kRed);
  h1dataPB->SetMarkerStyle(21);
  h1dataPB->SetMarkerColor(kBlue);

  TH2D * h2dataMA = (TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/qA");
  h2dataMA->Divide((TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/wnA"));
  TH2D * h2dataMB = (TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/qB");
  h2dataMB->Divide((TH2D *) data->Get("vnanalyzer/Harmonics/20_25/N1HFm1g/wnB"));
  TH1D * h1dataMA = (TH1D *) h2dataMA->ProjectionY("h1dataMA",1,10);
  TH1D * h1dataMB = (TH1D *) h2dataMB->ProjectionY("h1dataMB",1,10);
  h1dataMA->SetMarkerStyle(20);
  h1dataMA->SetMarkerColor(kRed);
  h1dataMB->SetMarkerStyle(21);
  h1dataMB->SetMarkerColor(kBlue);
  TCanvas * can = new TCanvas("can","can",1000,800);
  can->Divide(2,2);
  can->cd(1);
  h1amptPA->SetMinimum(-0.01);
  h1amptPA->SetMaximum(0.01);
  h1amptPA->Draw();
  h1amptPB->Draw("same");
  can->cd(2);
  h1amptMA->SetMinimum(-0.01);
  h1amptMA->SetMaximum(0.01);
  h1amptMA->Draw();
  h1amptMB->Draw("same");
  can->cd(3);
  h1dataPA->SetMinimum(-0.01);
  h1dataPA->SetMaximum(0.01);
  h1dataPA->Draw();
  h1dataPB->Draw("same");
  can->cd(4);
  h1dataMA->SetMinimum(-0.01);
  h1dataMA->SetMaximum(0.01);
  h1dataMA->Draw();
  h1dataMB->Draw("same");

}
