TGraphErrors * N1Test(int replay, int bin, double eMin, double eMax, double & ymin, double & ymax, TGraphErrors * &g,TGraphErrors * &gA, TGraphErrors * &gB, TGraphErrors * &gSpec, TGraphErrors * &gint, TGraphErrors *& gintA, TGraphErrors *& gintB, double & vint, double & vinte, double & vintA, double & vintAe, double & vintB, double & vintBe ){
  fin = new TFile(rootFile.data(),"r");
  TGraphErrors * g2 ;
  TGraphErrors * gA2 ;
  TGraphErrors * gB2 ;
  TGraphErrors * gSpec2 ;
  TGraphErrors * gint2 ;
  TGraphErrors * gintA2 ;
  TGraphErrors * gintB2 ;
  TGraphErrors * gtmp;
  double x[12];
  double y[12];
  double ey[12];
  gint2 = new TGraphErrors(12,x,y,0,ey);
  gintA2 = new TGraphErrors(12,x,y,0,ey);
  gintB2 = new TGraphErrors(12,x,y,0,ey);
  double vint2=0;
  double vinte2=0;
  double vintA2=0;
  double vintAe2=0;
  double vintB2=0;
  double vintBe2=0;
  int epindx = -1;
  string cname = "c"+ANALS[replay][0]+to_string(bin);
  TCanvas * ctest = new TCanvas(cname.data(),cname.data(),1200,900);
  ctest->cd();
  TH1D * h = new TH1D("h","h",200,-3,3);
  h->SetDirectory(0);
  h->SetXTitle("#eta");
  h->SetYTitle("v_{1}");
  h->SetMinimum(-0.06);
  h->SetMaximum(0.02);
  h->Draw();
  cout<<"N1 replay with replay = "<<replay<<"\t"<<ANALS[replay][0]<<endl;
  int A=0;
  int B = 0;
  if(replay==N1TEST) {
    A = N1HFp1gSUB3;
    B = N1HFm1gSUB3;
  } 
  cout<<"epindx: "<<epindx<<endl;
  if(epindx>=0) {
    cout<<"A: "<<A<<"\t"<<ANALS[A][0]<<"\t"<<EPNames[epindx]<<"\t"<<EPNames[RCMate1[epindx]]<<"\t"<<EPNames[RCMate2[epindx]]<<endl;
  }
  //
  // Start with eta distribution
  //
  int AepA = HFp1g;
  int BepA = HFm1g;
  int CepA = trackmid1;
  int AepB = HFm1g;
  int BepB = HFp1g;
  int CepB = trackmid1;
  TGraphErrors * gg1 = (TGraphErrors *) gintA->Clone("g1");
  TGraphErrors * gg2 = (TGraphErrors *) gintA->Clone("g2");
  TGraphErrors * gg3 = (TGraphErrors *) gintA->Clone("g3");
  TGraphErrors * gg4 = (TGraphErrors *) gintA->Clone("g4");
  TGraphErrors * gg5 = (TGraphErrors *) gintA->Clone("g5");
  TGraphErrors * gg6 = (TGraphErrors *) gintA->Clone("g6");
  TGraphErrors * gg7 = (TGraphErrors *) gintA->Clone("g7");
  TGraphErrors * gg8 = (TGraphErrors *) gintA->Clone("g8");
  for(int i = 0; i<12; i++) {
    double EtaMin = -2.4 + 0.4*i;
    double EtaMax = EtaMin+0.4;
    if(fabs(EtaMin)<0.001) EtaMin = 0.;
    if(fabs(EtaMax)<0.001) EtaMax = 0.;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,AepA, BepA, CepA);
    g2 = GetVNPt(B,bin,AepB,EtaMin,EtaMax,gA2, gB2, gSpec2, vint2, vinte2,vintA2, vintAe2, vintB2, vintBe2, false,0,0,AepB, BepB, CepB);
    gint->GetY()[i] = (vintA-vintA2)/2.;
    gint->GetEY()[i] = (vinte+vinte2)/2.;
    gintA->GetY()[i]=vintA;
    gintA->GetEY()[i]=vintAe;
    gintB->GetY()[i]=vintA2;
    gintB->GetEY()[i]=vintAe2;
    fin->Close();
    int aa = AepA;
    int bb = BepA;
    int cc = CepA;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg1->GetY()[i]=vintA;
    gg1->GetEY()[i]=vintAe;
    aa = HFp1g;
    bb = HFm1f;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    cc = trackp106;
    gg2->GetY()[i]=vintA;
    gg2->GetEY()[i]=vintAe;
    fin = new TFile(rootFile.data(),"r");
    aa = HFp1g;
    bb = HFm1e;
    cc = trackp106;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg3->GetY()[i]=vintA;
    gg3->GetEY()[i]=vintAe;
    aa = HFp1g;
    bb = HFm1d;
    cc = trackp106;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg4->GetY()[i]=vintA;
    gg4->GetEY()[i]=vintAe;
    aa = HFp1g;
    bb = HFm1c;
    cc = trackp106;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg5->GetY()[i]=vintA;
    gg5->GetEY()[i]=vintAe;
    aa = HFp1g;
    bb = trackm122;
    cc = trackp106;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg6->GetY()[i]=vintA;
    gg6->GetEY()[i]=vintAe;
    aa = HFp1g;
    bb = trackm118;
    cc = trackp106;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg7->GetY()[i]=vintA;
    gg7->GetEY()[i]=vintAe;
    aa = HFp1g;
    bb = trackm114;
    cc = trackp106;
    g  = GetVNPt(A,bin,AepA,EtaMin,EtaMax,gA, gB, gSpec, vint, vinte,vintA, vintAe, vintB, vintBe, false,0,0,aa, bb, cc);
    gg8->GetY()[i]=vintA;
    gg8->GetEY()[i]=vintAe;
    fin = new TFile(rootFile.data(),"r");
  }
  gint->SetName("gint");
  gintA->SetName("gintA");
  gintB->SetName("gintB");
  gg1->Draw("p");
  gg2->SetMarkerStyle(20);
  gg2->SetMarkerColor(kBlue);
  gg2->SetLineColor(kBlue);
  gg2->Draw("p");
  gg3->SetMarkerStyle(21);
  gg3->SetMarkerColor(kCyan);
  gg3->SetLineColor(kCyan);
  gg3->Draw("p");
  gg4->SetMarkerStyle(25);
  gg4->SetMarkerColor(kGreen);
  gg4->SetLineColor(kGreen);
  gg4->Draw("p");
  gg5->SetMarkerColor(kOrange);
  gg5->SetLineColor(kOrange);
  gg5->Draw("p");
  gg6->SetMarkerStyle(28);
  gg6->SetMarkerColor(kBlue-3);
  gg6->SetLineColor(kBlue-3);
  gg6->Draw("p");
  gg7->SetMarkerStyle(34);
  gg7->SetMarkerColor(kRed-3);
  gg7->SetLineColor(kRed-3);
  gg7->Draw("p");
  gg8->SetMarkerStyle(33);
  gg8->SetMarkerColor(kCyan+2);
  gg8->SetLineColor(kCyan+2);
  gg8->Draw("p");
  TLegend * leg = new TLegend(.2,.2,.5,.4);
  leg->SetBorderSize(0);
  leg->AddEntry(gg1,"-5.0<#eta<-4.0","lp");
  leg->AddEntry(gg2,"-5.0<#eta<-4.5","lp");
  leg->AddEntry(gg3,"-4.5<#eta<-4.0","lp");
  leg->AddEntry(gg4,"-4.0<#eta<-3.5","lp");
  leg->AddEntry(gg5,"-3.5<#eta<-3.0","lp");
  leg->AddEntry(gg6,"-2.4<#eta<-2.0","lp");
  leg->AddEntry(gg7,"-2.0<#eta<-1.6","lp");
  leg->AddEntry(gg8,"-1.6<#eta<-1.2","lp");
  leg->Draw();
  //gintA->SetTitle("NOGOOD");
  //gintB->SetTitle("NOGOOD");
  //
  // Now do requested calculation
  //
  g = GetVNPt(A,bin,AepA,eMin,eMax,gA, gB, gSpec, vint, vinte, vintA, vintAe, vintB, vintBe,false,0,0,AepA, BepA, CepA);
  g2 = GetVNPt(B,bin,AepB,eMin,eMax,gA2, gB2, gSpec2, vint2, vinte2,vintA2, vintAe2, vintB2, vintBe2, false,0,0,AepB, BepB, CepB);
  fin->Close();
  fin = new TFile(rootFile.data(),"r");
  for(int i = 0; i<g->GetN(); i++) {
    g->GetY()[i] = (gA->GetY()[i]-gA2->GetY()[i])/2.;
    double e = sqrt(pow(gA->GetEY()[i],2)+pow(gA2->GetEY()[i],2)+2*gA->GetEY()[i]*gA2->GetEY()[i]*min(gA->GetEY()[i],gA2->GetEY()[i]));
    g->GetEY()[i] = e;
    gB->GetY()[i] = gA2->GetY()[i];
    gB->GetEY()[i]=gA2->GetEY()[i];
  }
  ymin = setYmin(g);
  ymax = setYmax(g);
  g->SetName("g");
  gA->SetName("gA");
  gB->SetName("gB");
  //gA->SetTitle("NOGOOD");
  //gB->SetTitle("NOGOOD");
  return g;
}
